name = QAConfig
status = error
dest = err

appender.rolling.type = RollingFile
appender.rolling.name = LOGFILE
appender.rolling.append = true
appender.rolling.fileName = ${sys:logPath:-qa.log}
appender.rolling.filePattern = ${sys:logPath:-qa.log}-%i.gz
appender.rolling.createOnDemand = true
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{ISO8601} [%c{2}] %level %msg%n
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 128MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 5

rootLogger.level = info
rootLogger.appenderRef.stdout.ref = LOGFILE
