fauna {
  await-index-build = true
  test-generator = Simple
  op-generator = InitOnly
  remote-port = 2552
  ready-timeout = 30.minutes

  db {
    conf-path = "/etc/faunadb.yml"
    create-config = false
    hosts = []
    root-key = "secret"
    data-path = ""
    log-path = ""
    log-trace = false
    log-level = "INFO"
    broadcast-addr = ""
    listen-addr = ""
    network-id = ""
    cluster-name = ""
    round-trip-time = 1000
    trace-probability = 0.0
    enable-qos = false
    concurrent-reads = 128
    flags-enabled = true

    // QA environments typically need a longer health check timeout to
    // reliably initialize a cluster.
    health-check-timeout = 2000
  }

  cluster {
    // remote hosts available to run Workers.
    // They must have fauna.qa.Workers running
    hosts = []

    // Total number of "clients" that will connect
    // in parallel to the FaunaDB instance under test.
    // For remote systems, these will be distrubted
    // among the remote machines, but will only total
    // the configured number.
    clients = 5
  }

  test {
    writers = 5
    readers = 5
    duration = 10.minutes
    timeout = 5.minutes

    per-customer-rate = max

    // seed value for Prop
    //prop-seed = 1
  }
}

timed-run {
  duration = 30.minutes
}

baseline {
  largeset {
    instances = 10000
    results = 4000
  }
}

multitenant {
  test {
    tenants = 3
    concurrentReaders = 3
    priority-changes = 5.minutes
  }

  data {
    classes = 10
    maxInstances = 10000
  }
}

ping {
  rates {
    all = 1 per minute
    global = 1 per minute
    local = 1 per minute
    one = 1 per minute
  }
}

nvidiaindex {
  data {
    ids = 10000
  }
}

correctness {
  stream-count = 4

  index-and-verify = true
  max-instance-padding = 10

  query-ratios {
    create-objects = 4
    update-objects = 2
    delete-objects = 1
    read-objects = 1
    verify-indexes = 2
    create-with-constraint-violation = 1
    delete-with-constraint-violation = 1
  }

  min-remembered-objects = 100
  max-remembered-objects = 1000

  max-created-objects = 8
  max-deleted-objects = 6
}

reads {
  instances = 10000
  density = 100
  per-transaction = 20
}

writes {
  per-transaction = 2
}

joins {
  instances = 10000
  density = 500
  per-transaction = 5
}

intersections {
  instances = 100000
  density = 500
  per-transaction = 5
}

contended-writes {
  predefined-counters = 1000
  contention-factor = 0.4
}

simple {
  ids = 10000
}

bank {
  num-accounts = 20
  starting-balance = 100
  max-transfer = 10
}

uniqueness {
  buffer-size = 20
}

sets {
  total-unique-instances = 100
}

compaction {
  initial-docs = 1000
  bytes-per-doc = 1024
  key-range = 100
  batch-size = 10
  remove-ratio = 0.1
}

performance {
  dataintegrity = false
  records = 100000
  batchsize = 100
  fieldcount = 1
  fieldlength = 100
  tx {
    reads = 0.5
    updates = 0.5
    writes = 0.0
    deletes = 0.0
    maxsize = 2
    minsize = 1
  }
}
