fauna.db.hosts = ["NoDC:127.0.0.1:8443"]
fauna.db.data-path = "/var/db/fauna"
fauna.await-index-build = false

baseline {
  largeset {
    instances = 10
    results = 40
  }
}

nvidiaindex {
  data {
    ids = 10
  }
}

multitenant {
  test {
    tenants = 2
  }

  data {
    classes = 2
    maxInstances = 10
  }
}

correctness {
  stream-count = 4

  index-and-verify = true
  max-instance-padding = 10

  query-ratios {
    create-objects = 4
    update-objects = 2
    delete-objects = 1
    read-objects = 1
    verify-indexes = 2
    create-with-constraint-violation = 1
    delete-with-constraint-violation = 1
  }

  min-remembered-objects = 1
  max-remembered-objects = 10

  max-created-objects = 8
  max-deleted-objects = 6
}

reads {
  instances = 10
  density = 1
  per-transaction = 10
}

writes {
  per-transaction = 2
}

joins {
  instances = 10
  density = 5
  per-transaction = 5
}

intersections {
  instances = 10
  density = 5
  per-transaction = 5
}

contended-writes {
  predefined-counters = 10
  contention-factor = 0.4
}

simple {
  ids = 10
}

upgrade {
  current-version = right.now
  next-version = the.future
}

vary-log-replicas {
  pause = 30.seconds
}
