package fauna.tx.transaction

import fauna.atoms._
import fauna.codex.cbor.CBOR
import fauna.exec.IdxWaitersMap
import fauna.lang.{ TimeBound, Timestamp }
import fauna.lang.clocks.DeadlineClock
import fauna.lang.syntax._
import java.util.concurrent.atomic.{ AtomicBoolean, AtomicLong, LongAccumulator }
import scala.concurrent.{ Await, Future, TimeoutException }
import scala.concurrent.duration._
import DataMessage._

// FIXME: support retain/release management for messages and batches
// so we can use pooled bytebufs.
class DataNode[K, R, RV, W, WV](
  val ctx: PipelineCtx[K, R, RV, W, WV],
  val store: TransactionStorage[K, R, RV, W, WV])(implicit deadlineClock: DeadlineClock) extends Node[K, R, RV, W, WV] {

  import ctx.codecs._

  protected def onClose() = {
    handler.close()
    readBroker.close()
  }

  private implicit def ec = ctx.executionContext

  private[this] val applySequencer = store.applySequencer
  private[this] val broker = new ScopeBroker(this, applySequencer)
  private[transaction] val readBroker = new ReadBroker(this)
  private[this] val logSegmentsValid = new IdxWaitersMap(Epoch.MinValue)
  private[this] val pendingTopologyVersion = new AtomicLong(0L)
  private[this] val topologyVersion = new IdxWaitersMap(0L)
  private[this] val _isInRecovery = new AtomicBoolean(false)

  private[this] val maxReceivedBatchIdx =
    new LongAccumulator(
      Math.max(_, _),
      Epoch(applySequencer.maxAppliedTimestamp).idx
    )

  def maxReceivedBatch = new Epoch(maxReceivedBatchIdx.get())
  def minPersistedTimestamp = store.persistedTimestamp
  def isInRecovery = _isInRecovery.get

  /**
    * Waits until all pending and queued transactions have exceeded the
    * specified topology version.
    *
    * In order to maintain the consistency of transaction applications, the
    * DataNode expects the topology migration process to step through a
    * lifecycle for as locations move from uncovered to covered and back again.
    *
    * The process for migrating a location to a node is:
    *
    * 1. A topology version is introduced which marks a location (as part of a
    *    larger segment) as pending/write-only for this node. The DataNode's log
    *    subscriptions will start migrating to the new topology. Until this is
    *    complete, transactions which write to the location may be missing from
    *    batches. `waitForTopologyVersion` returns a Future which completes once
    *    transaction application has fully moved over to the new topology.
    *
    * 2. Once `waitForTopologyVersion` returns, the TopologyReconciler is able
    *    to initiate state transfer from other replicas of the location's data
    *    at a snapshot timestamp >= the DataNode's Last Applied Timestamp.
    *
    * 3. When state transfer completes, the reconciler introduces a second
    *    topology version in which the location is marked as current/readable.
    *    As the DataNode's log subscriptions move to the new topology, it will
    *    start participating in reads for the location data. Until this is
    *    complete, transactions which read from the location may be missing in
    *    batches, and therefore be skipped by read forwarding. However, since
    *    the read handler itself always uses the latest partitioner, the node
    *    will respond to backup reads and read retries.
    *
    * The process for migrating a location off node is much simpler. The
    * location will be dropped from one topology version to the next, and the
    * DataNode will immediately start dropping affected transactions, even
    * though some may have been buffered in already received partial batches.
    *
    * @param v the topology version to wait for
    * @param within the maximum duration of wait
    * @return future that completes with true if the wait was successful, or with false
    *         if the wait timed out.
    */
  def waitForTopologyVersion(v: Long, within: Duration) =
    topologyVersion.get(v, within)

  /**
    * Notifies topology version listeners when this DataNode has fully migrated
    * to the specified topology version, if `vers` is new. "Fully migrated"
    * means the transaction time by which all partial batches received by log
    * nodes will have been generated by a partitioner with a version GTE `vers`.
    */
  private[this] def maybeNotifyTopologyUpdate(vers: Long) =
    if (pendingTopologyVersion.get < vers) {
      pendingTopologyVersion.accumulateAndGet(vers, Math.max(_, _))
      val barrierTS = maxReceivedBatch.ceilTimestamp
      // N.B. Provide a long - but not infinite - timeout.
      store.waitForAppliedTimestamp(barrierTS, 1.day.bound) foreach { _ =>
        topologyVersion.update(vers)
      }
    }

  private[this] def updateSegments(): Future[Unit] = {
    val lni = ctx.logNodeProvider.getLogNodeInfo
    broker.updateSegments(lni.topology) map { _ =>
      logSegmentsValid.update(lni.validUntil)
    }
  }

  // REVIEWER: do we need to make sure the effects of this call are visible
  // before proceeding?
  Await.result(updateSegments(), 10.seconds)

  ctx.logNodeProvider.subscribeWithLogging {
    updateSegments() map { _ => !isClosed }
  }

  broker.start()

  def addOrReplaceStream(stream: DataStream[W, WV]): Unit =
    broker.addOrReplaceStream(stream)

  def removeStream(stream: DataStream[W, WV]): Unit =
    broker.removeStream(stream)

  private[this] val handler = ctx.dataHandler {
    case (from, Reinit(seg, prev, _), _) =>
      recvReinit(from.id, seg, prev)

    case (from, Batches(seg, pvers, latest, _, prev, last, batches), _) =>
      recvBatches(from.id, seg, pvers, latest, prev, last, batches)

    case (from, Read(_, read, ts, token, version), deadline) =>
      recvReadRequest(from.id, ts, CBOR.parse[R](read), token, version, deadline)

    case (from, ReadResult(_, read, ts, value, token, version), _) =>
      // FIXME: value is never None. Fix the protocol to avoid boxing as an Option.
      readBroker.recvResult(
        from.id,
        ts,
        CBOR.parse[R](read),
        CBOR.parse[RV](value.get),
        token,
        version)
  }

  // message handlers

  private def recvReinit(host: HostID, seg: SegmentID, prev: Epoch): Future[Unit] = {
    broker.reinit(host, seg, prev)
  }

  private def recvBatches(host: HostID, segment: SegmentID, pvers: Long, latest: Epoch, prev: Epoch, last: Epoch, batches: Vector[Batch]) = {
    val revalPeriod = TxnPipeline.LogSegmentsRevalidationPeriod
    logSegmentsValid.get(last, revalPeriod) flatMap { success =>
      if (success) {
        maxReceivedBatchIdx.accumulate(last.idx)

        val part = ctx.partitioner
        val cpvers = part.version

        if (pvers == cpvers) {
          // mark timestamp after which we'll be fully migrated to a new topology
          maybeNotifyTopologyUpdate(pvers)

          val bs = if (batches.nonEmpty) {
            batches
          } else {
            List(Batch(last, ScopeID.RootID, Vector.empty, 0))
          }

          ctx.logger.debug(s"DataNode: Received $segment $bs.")

          val add = broker.queue.add(segment, prev, bs) recover {
            case _: TimeoutException =>
              ctx.logger.warn(s"DataNode: timed out adding to transaction queue.")
              None
          }

          add map { nextOption =>
            nextOption foreach { next =>
              // Notify preferred log nodes of batch acceptance, so we will receive
              // the live stream of txns.
              broker.acceptBatches(segment, pvers, next)

              // If we're not yet caught up to the live stream, continue with the
              // current log node.
              if (next < latest) {
                if (latest.idx - next.idx > LogNode.MaxPipelinedEpochs) {
                  if (_isInRecovery.compareAndSet(false, true)) {
                    ctx.logger.warn(
                      s"DataNode: entering recovery mode (segment=$segment, latest=$latest, next=$next)")
                  }
                } else {
                  if (_isInRecovery.compareAndSet(true, false)) {
                    ctx.logger.info(
                      s"DataNode: leaving recovery mode (segment=$segment, latest=$latest, next=$next)")
                  }
                }
                broker.getBatches(host, segment, pvers, next)
              }
            }
          }
        } else {
          Future.unit
        }
      } else {
        ctx.logger.warn(s"DataNode: timed out after ${revalPeriod.toCoarsest} waiting to re-validate log segment topology up to $last")
        Future.unit
      }
    }
  }

  private def recvReadRequest(
    to: HostID,
    ts: Timestamp,
    read: R,
    token: Option[Long],
    version: Long,
    deadline: TimeBound): Future[Unit] = {

    def read0: Future[Unit] = {
      val part = ctx.partitioner
      if (part.coversRead(read)) {
        store.evalTxnRead(ts, read, deadline) flatMap { v =>
          // revalidate partitioner
          if (ctx.partitioner.version == part.version) {
            sendReadResult(to :: Nil, ts, token, read, v, version)
          } else if (deadline.hasTimeLeft) {
            // retry
            read0
          } else {
            getLogger().trace(
              "DataNode.recvRead: Timed out waiting for topology to stabilize.")
            Future.unit
          }
        }
      } else {
        Future.unit
      }
    }

    val key = ctx.keyExtractor.readKey(read)

    // if the applied timestamp for key is GTE the read ts, serve the read.
    if (store.appliedTimestamp(key) >= ts) {
      read0 recover { case _: TimeoutException => () }

    // if the sender is not local, wait until we can serve the read, within
    // the deadline.
    } else if (!ctx.hostService.isLocal(to)) {
      store.waitForAppliedTimestamp(key, ts, deadline) flatMap { _ =>
        read0
      } recover {
        case _: TimeoutException => ()
      }

    // else if the sender is local, drop the read request, since the local
    // copy of the transaction will forward the read result after apply.
    } else {
      Future.unit
    }
  }

  // helpers

  private[transaction] def sendReadResult(
    to: Iterable[HostID],
    ts: Timestamp,
    token: Option[Long],
    read: R,
    v: RV,
    version: Long) = {
    val result = ReadResult(
      ScopeID.RootID,
      CBOR.encode(read).toByteArray,
      ts,
      Some(CBOR.encode(v).toByteArray),
      token,
      version)
    (to map { ctx.dataSink(_).send(result) }).join
  }
}
