package fauna.api.schema

import fauna.api.APIEndpoint.Response
import fauna.atoms.SchemaVersion
import fauna.atoms.ScopeID
import fauna.lang.syntax._
import fauna.lang.Timestamp
import fauna.model.runtime.fql2.FQLInterpCtx
import fauna.model.schema.{ Result, SchemaError }
import fauna.model.schema.fsl.SourceFile
import fauna.model.Cache
import fauna.model.Database
import fauna.net.http.{ HttpBodyPart, HttpRequest }
import fauna.net.util.URIQueryString
import fauna.repo.query.Query
import fql.ast.Src
import fql.color.ColorKind
import fql.schema.Diff
import fql.schema.DiffRender
import io.netty.buffer.ByteBuf
import io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.TooManyFormFieldsException
import io.netty.handler.codec.DecoderException
import scala.concurrent.{ ExecutionContext, Future }

object SchemaRequest {
  import Result.Ok

  // Maximum number of schema files, always including `main.fsl`. So, there can only
  // be MaxFiles - 1 other files, even if main.fsl doesn't exist, so that we can
  // create `main.fsl` for autogenerated schema.
  val MaxFiles = 1024

  sealed trait DiffFormat {
    def render(
      before: Map[Src.Id, String],
      after: Map[Src.Id, String],
      diffs: Seq[Diff],
      color: ColorKind): String = this match {
      case DiffFormat.Semantic =>
        DiffRender.renderSemantic(before, after, diffs, color)
      case DiffFormat.Summary =>
        DiffRender.renderSummary(before, after, diffs, color)
      case DiffFormat.Textual =>
        DiffRender.renderTextual(before, after, color)
    }
  }

  object DiffFormat {
    object Semantic extends DiffFormat
    object Summary extends DiffFormat
    object Textual extends DiffFormat
  }

  final class Parsed(
    request: HttpRequest,
    val body: Option[ByteBuf] = None,
    val sourceFiles: Seq[SourceFile.FSL] = Seq.empty
  ) {
    def path = request.path
    def method = request.method

    lazy val params =
      request.query.fold(Map.empty[String, String])(URIQueryString.parse)

    def toAuthenticated(ctx: FQLInterpCtx) =
      new Authenticated(this, ctx)
  }

  final class Authenticated(request: Parsed, val ctx: FQLInterpCtx) {
    def scopeID = ctx.auth.scopeID

    // Common params
    def version = request.params.get("version") flatMap { _.toLongOption }
    def isForce = request.params.get("force") exists { _ == "true" }
    def isValidate = request.params.get("validate") exists { _ == "true" }
    def isOverride = request.params.get("override") forall { _ != "false" }
    def isStaged = request.params.get("staged") exists { _ == "true" }
    def diffFormat = request.params.get("format") match {
      case Some("semantic") => Some(DiffFormat.Semantic)
      case Some("summary")  => Some(DiffFormat.Summary)
      case Some("textual")  => Some(DiffFormat.Textual)
      case _ =>
        request.params.get("diff") match {
          // NB: `true` is a legacy alias for `semantic`
          case Some("semantic" | "true") => Some(DiffFormat.Semantic)
          case Some("summary")           => Some(DiffFormat.Summary)
          case Some("textual")           => Some(DiffFormat.Textual)
          case _                         => None
        }
    }
    def colorKind = request.params.get("color") match {
      case Some("ansi") => ColorKind.Ansi
      case _            => ColorKind.None
    }

    // Common body patterns
    def files = request.sourceFiles
    def fslSnippet = request.body.map { _.toUTF8String }.filter { _.trim.nonEmpty }

    // Common checks
    def checkWritePermission(): Query[Result[Unit]] =
      ctx.auth.checkWriteSchemaPermission(ctx.auth.scopeID) map {
        if (_) Ok(()) else SchemaError.Forbidden.toResult
      }

    def disallowTenantRoot(): Query[Result[Unit]] =
      Database
        .forScope(ctx.auth.scopeID)
        .flatMap {
          case Some(db) if db.isCustomerTenantRoot =>
            SchemaError
              .Validation("Schema can not be created in your account root.")
              .toQuery
          case _ => Query.value(Ok(()))
        }

    def disallowRoot(): Query[Result[Unit]] =
      if (ctx.auth.scopeID == ScopeID.RootID) {
        SchemaError
          .Validation("Schema cannot be staged in the root database")
          .toQuery
      } else {
        Query.value(Ok(()))
      }

    def checkSchemaVersion(): Query[Result[SchemaVersion]] =
      (isForce, version) match {
        case (true, _) =>
          Cache.getLastSeenSchema(scopeID).getOrElseT(SchemaVersion.Min).map {
            Ok(_)
          }

        case (_, Some(knownVersion)) =>
          val currQ =
            Cache.guardFromStalenessIf(scopeID, Cache.getLastSeenSchema(scopeID)) {
              _.getOrElse(SchemaVersion.Min).toMicros < knownVersion
            }

          currQ.getOrElseT(SchemaVersion.Min) map { currVersion =>
            if (currVersion.toMicros == knownVersion) {
              Ok((currVersion))
            } else {
              SchemaError.Conflict("Stale schema version provided").toResult
            }
          }

        case _ =>
          Cache.getLastSeenSchema(scopeID) map {
            case Some(ver) => Ok(ver)
            case None      => Ok(SchemaVersion.Min)
          }
      }
  }

  // TODO: handle JSON files
  def parse(request: HttpRequest, body: Future[Option[ByteBuf]])(
    implicit ec: ExecutionContext): Future[Either[Response, Parsed]] =
    body map {
      case None => Right(new Parsed(request))
      case body @ Some(buf) =>
        if (!request.body.isMultipart) {
          Right(new Parsed(request, body))
        } else {
          def badRequest(msg: String) =
            Left(
              SchemaResponse.ErrorResponse.BadRequest(msg).toResponse(Timestamp.Min))

          try {
            HttpBodyPart
              .parse(request.raw, buf, MaxFiles)
              .map { part =>
                SourceFile.FSL.checkFilename(part.name) match {
                  case fql.Result.Ok(_) =>
                    Right(SourceFile.FSL(part.name, part.content))
                  case fql.Result.Err(_) =>
                    badRequest(s"Invalid filename `${part.name}`")
                }
              }
              .sequence
              .flatMap { files =>
                val hasMain = files.exists(SourceFile.Builtin.isBuiltin)
                val maxFiles = if (hasMain) MaxFiles else MaxFiles - 1

                if (files.length > maxFiles) {
                  badRequest("Too many files")
                } else {
                  Right(new Parsed(request, body, files))
                }
              }
          } catch {
            case HttpBodyPart.NonMultiPartRequestException =>
              badRequest("Request is not a valid multipart request")
            case _: TooManyFormFieldsException => badRequest("Too many files")

            // Catch-all for nonsense HTTP bodies.
            case _: DecoderException => badRequest("Invalid request")
          }

        }
    }
}
