package fauna.trace

import fauna.codex.cbor._
import fauna.codex.json._
import io.netty.util.AsciiString
import java.lang.{ Long => JLong }
import scala.util.Random

object TraceID {

  implicit val codec = new CBOR.Codec[TraceID] {
    def encode(stream: CBORWriter, id: TraceID) = {
      CBOR.LongCodec.encode(stream, id.hi)
      CBOR.LongCodec.encode(stream, id.lo)
    }

    def decode(stream: CBORParser): TraceID = {
      val hi = CBOR.LongCodec.decode(stream)
      val lo = CBOR.LongCodec.decode(stream)
      new TraceID(hi, lo)
    }
  }

  implicit object JSEncoder extends JsonEncoder[TraceID] {
    def encodeTo(stream: JsonGenerator, value: TraceID): Unit =
      stream.put(value.toHexString)
  }

  /**
    * The size in chars of the TraceID component of a W3C traceparent
    * header.
    */
  val W3CSize = 2 * Hex.CharsPerLong

  /**
    * The char offset in a compliant W3C traceparent header which
    * begins the Trace ID segment.
    */
  val W3COffset = 3

  /**
    * Generates a valid TraceID with a random value.
    */
  def randomID(implicit rnd: Random): TraceID = {
    var hi = 0L
    var lo = 0L

    while (hi == 0 || lo == 0) {
      hi = rnd.nextLong()
      lo = rnd.nextLong()
    }

    new TraceID(hi, lo)
  }


  /**
    * Decodes a hexidecimal-encoded trace ID in network byte order.
    */
  def fromHexString(str: CharSequence, offset: Int = 0): TraceID = {
    val hi = JLong.parseUnsignedLong(str, offset, offset + Hex.CharsPerLong, 16)
    val lo = JLong.parseUnsignedLong(
      str,
      offset + Hex.CharsPerLong,
      offset + 2 * Hex.CharsPerLong,
      16)

    if (hi == 0 && lo == 0) {
      throw new IllegalArgumentException("TraceID must have at least one non-zero byte")
    } else {
      new TraceID(hi, lo)
    }
  }
}

/**
  * A Trace ID is a 128 bit, globally-unique value which is used to
  * identify a trace through the system. It is commonly represented as
  * a 16 byte array, for example 4bf92f3577b34da6a3ce929d0e0e4736.
  *
  * An all-zero value is invalid.
  *
  * TraceIDs with all-zero high bits were generated by systems using
  * only 64 bit IDs. See:
  * https://www.w3.org/TR/trace-context-1/#interoperating-with-existing-systems-which-use-shorter-identifiers
  */
final class TraceID(
  private[TraceID] val hi: Long,
  private[TraceID] val lo: Long) {

  override def equals(other: Any): Boolean =
    other match {
      case o: TraceID =>
        hi == o.hi && lo == o.lo
      case _ => false
    }

  override def hashCode(): Int =
    JLong.hashCode(hi) ^ JLong.hashCode(lo)

  override def toString =
    s"TraceID($toHexString)"

  /**
    * Returns the value of this trace ID encoded in hexidecimal in
    * network byte order.
    */
  def toHexString: AsciiString = {
    val buf = new Array[Char](2 * Hex.CharsPerLong)
    toHexString(buf, 0)
    new AsciiString(buf)
  }

  def toHexString(buf: Array[Char], offset: Int): Unit = {
    Hex.toHex(hi, buf, offset)
    Hex.toHex(lo, buf, offset + Hex.CharsPerLong)
  }

  /**
    * Returns the low order bits for tracing systems which do not
    * support 128-bit trace IDs.
    *
    * See https://w3c.github.io/trace-context/ Section 8.4
    */
  def toLong: Long = lo

}
